# Generated by Django 3.0.2 on 2020-03-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.ImageField(default='default.jpg', upload_to='polls_images'),
        ),
    ]
