# Generated by Django 3.0.4 on 2020-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200322_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(default='polls.png', upload_to='polls_images'),
        ),
    ]
